all:
	g++ -g -std=c++0x ejercicio1.cpp -o ejercicio1
	g++ -g -std=c++0x ejercicio1-goloso.cpp -o ejercicio1-goloso
	g++ -g -std=c++0x brute-force-test.cpp -o brute-force
clean:
	rm  -f *.o ejercicio1 timer-test brute-force-test
