all:
	g++ -g -std=c++0x ejercicio1.cpp -o ejercicio1
	g++ -g -std=c++0x brute-force-test.cpp -o brute-force
	g++ -g -std=c++0x timer-test.cpp -o timer-test
clean:
	rm  -f *.o ejercicio1 timer-test brute-force-test
